theme: jekyll-theme-cayman
title: Adrian Dyson
description: All the latest in the world of Angular!
include:
  - _posts
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
github:
  is_project_page: false